[versions]
agp = "8.5.0"
kotlin = "2.0.0"
kotlin-kapt = "2.0.10"
ksp = "2.0.0-1.0.21"
androidxActivity = "1.9.1"
androidxCore = "1.13.1"
androidxLifecycle = "2.8.4"
androidxCompose = "1.7.0-beta07"
androidxComposeMaterial3 = "1.3.0-beta05"
androidxNavigation = "2.8.0-beta04"
androidxHiltNavigationCompose = "1.2.0"
hilt = "2.51.1"
retrofit = "2.11.0"
okHttp = "4.12.0"
glide = "4.12.0"
coroutines = "1.8.1"
junit = "4.13.2"
androidxTestJunit = "1.2.1"
espresso = "3.6.1"
datastoreCoreAndroid = "1.1.1"
datastorePreferences= "1.0.0"
media3Exoplayer = "1.4.0"
media3Ui = "1.4.0"
exoPlayer = "2.18.7"
coil = "2.7.0"
material = "1.5.0-alpha04"  # Use the latest version from the list you provided
kotlinx-serialization-json = "1.6.2"
kotlinx-datetime = "0.5.0"
playServicesAuth = "20.5.0"
playServicesFitness = "21.2.0"
charty = "2.1.0"
ktor = "2.3.0"
slf4j = "1.7.32"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "androidxCompose" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidxComposeMaterial3" }
androidx-compose-material = { group = "androidx.compose.material", name = "material", version.ref = "material" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "androidxCompose" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "androidxCompose" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "androidxCompose" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "androidxCompose" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "androidxCompose" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "androidxCompose" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }
androidx-lifecycle-viewModelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestJunit" }
androidx-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofit-kotlinx-serialization = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "retrofit" }
gson = { module = "com.google.code.gson:gson", version.ref = "retrofit" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okHttp" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-datastore-core-android = { group = "androidx.datastore", name = "datastore-core-android", version.ref = "datastoreCoreAndroid" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastorePreferences" }
androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3Exoplayer" }
androidx-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3Ui" }
exoplayer-core = { module = "com.google.android.exoplayer:exoplayer-core", version.ref = "exoPlayer" }
exoplayer-ui = { module = "com.google.android.exoplayer:exoplayer-ui", version.ref = "exoPlayer" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
play-services-fitness = { group = "com.google.android.gms", name = "play-services-fitness", version.ref = "playServicesFitness" }
play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "playServicesAuth" }
charty = { module="co.yml:ycharts", version.ref = "charty" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-gson = { module = "io.ktor:ktor-serialization-gson", version.ref = "ktor" }
slf4japi = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4jlog4j12 = { module = "org.slf4j:slf4j-log4j12", version.ref = "slf4j" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-test = { id = "com.android.test", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt-plugin = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin-kapt" }

[bundles]
retrofitBundle = ["retrofit", "retrofit-converter-gson", "retrofit-kotlinx-serialization", "okhttp-logging-interceptor", "gson"]
exoPlayerBundle = ["exoplayer-core", "exoplayer-ui"]
serializationBundle = ["kotlinx-serialization-json", "kotlinx-datetime"]
googleFitBundle = ["play-services-auth", "play-services-fitness"]
ktorBundle = ["ktor-client-core", "ktor-client-serialization", "ktor-client-android", "ktor-client-content-negotiation", "ktor-client-gson"]
